#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : setuptools_scm
Version  : 1.15.7
Release  : 36
URL      : https://pypi.debian.net/setuptools_scm/setuptools_scm-1.15.7.tar.gz
Source0  : https://pypi.debian.net/setuptools_scm/setuptools_scm-1.15.7.tar.gz
Summary  : the blessed package to manage your versions by scm tags
Group    : Development/Tools
License  : MIT
Requires: setuptools_scm-legacypython
Requires: setuptools_scm-python3
Requires: setuptools_scm-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools_scm

%description
===============

%package legacypython
Summary: legacypython components for the setuptools_scm package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the setuptools_scm package.


%package python
Summary: python components for the setuptools_scm package.
Group: Default
Requires: setuptools_scm-legacypython
Requires: setuptools_scm-python3

%description python
python components for the setuptools_scm package.


%package python3
Summary: python3 components for the setuptools_scm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the setuptools_scm package.


%prep
%setup -q -n setuptools_scm-1.15.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516462853
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export SOURCE_DATE_EPOCH=1516462853
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
