#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : setuptools_scm
Version  : 3.0.6
Release  : 56
URL      : https://files.pythonhosted.org/packages/08/d4/f894806d6faf117027b9d27c038820dddc2878d4b603bbb20b831776c96a/setuptools_scm-3.0.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/08/d4/f894806d6faf117027b9d27c038820dddc2878d4b603bbb20b831776c96a/setuptools_scm-3.0.6.tar.gz
Summary  : the blessed package to manage your versions by scm tags
Group    : Development/Tools
License  : MIT
Requires: setuptools_scm-python3
Requires: setuptools_scm-license
Requires: setuptools_scm-python
BuildRequires : buildreq-distutils23
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev
BuildRequires : setuptools-legacypython
BuildRequires : setuptools_scm

%description
===============

%package legacypython
Summary: legacypython components for the setuptools_scm package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the setuptools_scm package.


%package license
Summary: license components for the setuptools_scm package.
Group: Default

%description license
license components for the setuptools_scm package.


%package python
Summary: python components for the setuptools_scm package.
Group: Default
Requires: setuptools_scm-python3

%description python
python components for the setuptools_scm package.


%package python3
Summary: python3 components for the setuptools_scm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the setuptools_scm package.


%prep
%setup -q -n setuptools_scm-3.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533060511
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export SOURCE_DATE_EPOCH=1533060511
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/setuptools_scm
cp LICENSE %{buildroot}/usr/share/doc/setuptools_scm/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/setuptools_scm/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
